field: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581
fieldLayouts:
  25ddc7d5-b636-4886-a112-15195c636ae7:
    tabs:
      -
        elements:
          -
            fieldUid: ad4e3d36-752c-48da-bfbd-bd61e083119b
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5dc172d1-4954-444f-b558-6f9f388d0ac3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7897bf8b-9bea-4c58-8f04-aea29c95d7bf
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1b8f26ab-01a9-4570-9e96-1d18389f8226
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1b8f26ab-01a9-4570-9e96-1d18389f8226:
    contentColumnType: text
    fieldGroup: null
    handle: readMoreLink
    instructions: ''
    name: 'Read More Link'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - dotgovsupport@oaklandca.gov
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - 'https://www.oaklandca.gov'
                -
                  - allowAlias
                  - ''
                -
                  - allowMailto
                  - ''
                -
                  - allowHash
                  - ''
                -
                  - allowPaths
                  - ''
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f'
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb'
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a'
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3'
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a'
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf'
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0'
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
                    - 'section:07faad04-9ec4-4f68-9fe8-0ca20f189f8a'
                    - 'section:fbf8b9b0-8875-4e08-819a-d62603676dc4'
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7'
                    - 'section:17d5d48d-2d75-4742-8820-cdce13764482'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'folder:baf733c3-48be-42a7-8b4f-7a6bf9763542'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  5dc172d1-4954-444f-b558-6f9f388d0ac3:
    contentColumnType: text
    fieldGroup: null
    handle: linkSetDescription
    instructions: 'Use this optional field to provide context for the links you create in this section.'
    name: 'Link Set Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: 'Simple with Links.json'
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  7897bf8b-9bea-4c58-8f04-aea29c95d7bf:
    contentColumnType: string
    fieldGroup: null
    handle: linkSet
    instructions: ''
    name: 'Link Set'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - ac30e2e0-2f26-4b6c-a404-07b749af00dc
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - 109ddbd1-80ea-471e-a6f9-ef77d84a0800
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_46_linkset}}'
      fieldLayout: table
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  ad4e3d36-752c-48da-bfbd-bd61e083119b:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: linksWithDescriptions
name: 'Links with Descriptions'
sortOrder: 13
