field: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581
fieldLayouts:
  3a07acb2-2b7c-4bbf-8a61-9d46ee581b30:
    tabs:
      -
        elements:
          -
            fieldUid: e0441456-2c87-45db-aacd-22ac957f8fc1
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd5628cc-7472-48c6-8263-14745dbb90c9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 07e65c29-fba5-4a88-ade2-bd8abfb4cc69
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6d6039ca-322a-4f7f-91e2-371a9f5d637c
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  07e65c29-fba5-4a88-ade2-bd8abfb4cc69:
    contentColumnType: string
    fieldGroup: null
    handle: linkSet
    instructions: 'Add a link and an image up to three blocks. Choose a square icon, 300x300px in size. For best results, use a white outlined illustration/lineart.'
    name: 'Link Set'
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 61bef9fa-6716-4df3-a88d-46f256cdee73
            -
              __assoc__:
                -
                  - width
                  - ''
          -
            - eb7e7c8e-f03b-44c8-8b3f-f7086707f07a
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_51_linkset}}'
      fieldLayout: table
      maxRows: '3'
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  6d6039ca-322a-4f7f-91e2-371a9f5d637c:
    contentColumnType: text
    fieldGroup: null
    handle: readMoreLink
    instructions: 'Use this field to add a small green text link at the bottom of this block to another page or section on the site.'
    name: 'Read More Link'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - 'https://www.oaklandca.gov'
                -
                  - allowAlias
                  - ''
                -
                  - allowMailto
                  - ''
                -
                  - allowHash
                  - ''
                -
                  - allowPaths
                  - ''
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f'
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb'
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a'
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3'
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a'
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf'
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0'
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
                    - singles
                    - 'section:07faad04-9ec4-4f68-9fe8-0ca20f189f8a'
                    - 'section:fbf8b9b0-8875-4e08-819a-d62603676dc4'
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7'
                    - 'section:17d5d48d-2d75-4742-8820-cdce13764482'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  e0441456-2c87-45db-aacd-22ac957f8fc1:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fd5628cc-7472-48c6-8263-14745dbb90c9:
    contentColumnType: text
    fieldGroup: null
    handle: linkSetDescription
    instructions: ''
    name: 'Link Set Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: 'Simple with Links.json'
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: linkBlocksWithIcons
name: 'Link Blocks with Icons'
sortOrder: 11
