field: fd0c8e02-99b4-4ce5-ab89-b29cd0efc581
fieldLayouts:
  86bfb186-a92a-4057-89bf-1c4424a3af96:
    tabs:
      -
        elements:
          -
            fieldUid: 8960f671-8e74-4a40-a507-6ba440cb6c8e
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1e960f43-f531-48ab-81a0-67d143aebac6
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 295df0c5-cc10-4392-9fbb-3452cc97b84a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a2cf024d-962c-4e66-a16e-9b6faefbae19
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5ee14b98-d8d9-46bd-88d8-0aa45871cfc9
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1e960f43-f531-48ab-81a0-67d143aebac6:
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: ''
    name: Heading
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: text
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  295df0c5-cc10-4392-9fbb-3452cc97b84a:
    contentColumnType: string
    fieldGroup: null
    handle: entries
    instructions: 'Choose up to 3 news items you wish to display in this section.'
    name: Entries
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '3'
      localizeRelations: false
      selectionLabel: 'Add a news entry'
      showSiteMenu: true
      source: null
      sources:
        - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a'
      targetSiteId: null
      validateRelatedElements: true
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  5ee14b98-d8d9-46bd-88d8-0aa45871cfc9:
    contentColumnType: boolean
    fieldGroup: null
    handle: hideSummary
    instructions: 'Check this box if you wish to hide the summary text that appears at the bottom of each entryâ€™s block.'
    name: 'Hide Summary?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  8960f671-8e74-4a40-a507-6ba440cb6c8e:
    contentColumnType: boolean
    fieldGroup: null
    handle: allowAutofill
    instructions: 'If enabled, your news will automatically fill with the latest news entries that have been related to this page, up to 3, minus however many manual selections you make below.'
    name: 'Allow Autofill?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
  a2cf024d-962c-4e66-a16e-9b6faefbae19:
    contentColumnType: boolean
    fieldGroup: null
    handle: hideThumbnails
    instructions: 'Check this box if you wish to hide the thumbnail images and/or default icons for this block.'
    name: 'Hide Thumbnails?'
    searchable: false
    settings:
      default: false
      offLabel: null
      onLabel: null
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Lightswitch
handle: newsEntries
name: 'News Entries'
sortOrder: 17
