fieldLayouts:
  815fb02b-00d1-436a-a5ef-598b938f2831:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: d8042d7b-1c67-4b28-bb84-2002e74ed94b
            instructions: ''
            label: ''
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c2ad07dc-05e7-4ef4-89b6-2e1eaccee210
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 93eaa329-904e-4a23-9047-4decf3d47cac
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7594e9ae-f194-47c8-9a6b-076789f1087b
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a25a56ba-bfb3-4e4d-a857-6d3cb4a5dcdc
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 41124ab0-0e88-44c6-b4f2-f002669d8133
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 73b7b0c7-bff1-4c55-97aa-fc62042f0347
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d624c5c7-9cce-4088-92ba-02e1f2024c6a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e67ec759-ea3a-4568-bfa6-a314ff3d1036
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 44b00870-0842-4c4e-838f-dcd688fb5b05
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Relationships
        sortOrder: 2
handle: serviceRedirect
hasTitleField: true
name: 'Service Redirect'
section: b7e437e1-239f-4c5c-8c62-5f0323f9d22c
sortOrder: 3
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
