fieldLayouts:
  ec980d66-163d-4a97-be21-f1626a2370e4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: fff5cf49-87e6-4751-9032-b4ca8136e237
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: headers
hasUrls: true
name: Headers
settings:
  addSubfolderToRootUrl: true
  autoFocalPoint: ''
  bucket: cao-94612
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_API_KEY
  makeUploadsPublic: '1'
  region: us-west-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: headers
sortOrder: 5
type: craft\awss3\Volume
url: 'https://cao-94612.s3.amazonaws.com/'
