fieldLayouts:
  c20c2cad-83dc-483b-b650-f418bc587982:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: icons
hasUrls: true
name: Icons
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: cao-94612
  bucketSelectionMode: choose
  cfDistributionId: ''
  cfPrefix: ''
  expires: ''
  keyId: $S3_API_KEY
  makeUploadsPublic: '1'
  region: us-west-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: icons
sortOrder: 12
type: craft\awss3\Volume
url: 'https://s3.us-west-2.amazonaws.com/cao-94612/'
