contentColumnType: string(255)
fieldGroup: ed709c7c-0c3a-4457-ae2d-38a3ccb797e4
handle: appStoreDownloadLink
instructions: 'Enter the URL the user can go to to download this app on the Apple App Store.'
name: 'App Store Download Link'
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
