contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: departments
instructions: "Choose the department pages to relate to this entry. Relationships help content surface in search. Relationships also help documents surface on index pages. \r\n"
name: Departments
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a department'
  source: null
  sources:
    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
