contentColumnType: string
fieldGroup: 909c71fc-999c-4729-86d5-49cc9061f521
handle: embeddedContent
instructions: 'Select from the list of **approved** embeddable content that your page can display.'
name: 'Embedded Content'
searchable: true
settings:
  allowSelfRelations: false
  limit: '1'
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: true
  source: null
  sources:
    - 'section:74ecde2f-b254-4f3e-b889-1affac6f5999'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
