contentColumnType: string(255)
fieldGroup: 1fe293ad-52d9-4002-984e-b7a256d4b158
handle: medium
instructions: 'Add the URL for the Medium account for this entry.'
name: Medium
searchable: true
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
