contentColumnType: string
fieldGroup: 8e8ee56e-cdb8-4206-a3b5-c3aa0eb3a884
handle: projectBeforePhoto
instructions: 'Use this photo to display the project site before work begins.'
name: 'Project Before Photo'
searchable: true
settings:
  allowSelfRelations: false
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:a31d23bf-e3ee-4942-95e0-3d14c29620bb'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: 'Add a before photo'
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: true
  singleUploadLocationSource: 'volume:a31d23bf-e3ee-4942-95e0-3d14c29620bb'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
