contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: services
instructions: 'Choose the service landing pages to relate to this entry.'
name: Services
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a service'
  source: null
  sources:
    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
