contentColumnType: string
fieldGroup: 83c14444-efcf-4d13-a20a-56275fd18855
handle: teams
instructions: 'Pick the team(s) associated with this entry'
name: Teams
searchable: true
settings:
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a team'
  source: null
  sources:
    - 'section:fbf8b9b0-8875-4e08-819a-d62603676dc4'
  targetSiteId: null
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
