contentColumnType: datetime
fieldGroup: a8c82666-3295-4f90-b50b-67f2299847db
handle: termEnd
instructions: 'Choose the day this personâ€™s term will end.'
name: 'Term End'
searchable: true
settings:
  minuteIncrement: '30'
  showDate: true
  showTime: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
