contentColumnType: string
fieldGroup: 767a8f0b-6ea5-4855-a6f3-8c2a4a4aee78
handle: timeline
instructions: ''
name: Timeline
searchable: true
settings:
  contentTable: '{{%matrixcontent_timeline}}'
  maxBlocks: '6'
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
