contentColumnType: text
fieldGroup: 1fe293ad-52d9-4002-984e-b7a256d4b158
handle: youtube
instructions: 'Add the URL for the YouTube account for this entry.'
name: YouTube
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: ''
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
