field: 07e65c29-fba5-4a88-ade2-bd8abfb4cc69
fieldLayouts:
  9ce647d3-a42d-4d2d-8cfc-002e0df4dc58:
    tabs:
      -
        elements:
          -
            fieldUid: 61bef9fa-6716-4df3-a88d-46f256cdee73
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: eb7e7c8e-f03b-44c8-8b3f-f7086707f07a
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  61bef9fa-6716-4df3-a88d-46f256cdee73:
    contentColumnType: text
    fieldGroup: null
    handle: linkLocation
    instructions: ''
    name: 'Link Location'
    searchable: false
    settings:
      allowCustomText: '1'
      allowTarget: '1'
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - dotgovsupport@oaklandca.gov
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - 'https://www.oaklandca.gov'
                -
                  - allowAlias
                  - ''
                -
                  - allowMailto
                  - ''
                -
                  - allowHash
                  - ''
                -
                  - allowPaths
                  - ''
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f'
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb'
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a'
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3'
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a'
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf'
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0'
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
                    - 'section:07faad04-9ec4-4f68-9fe8-0ca20f189f8a'
                    - 'section:fbf8b9b0-8875-4e08-819a-d62603676dc4'
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7'
                    - 'section:17d5d48d-2d75-4742-8820-cdce13764482'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'folder:baf733c3-48be-42a7-8b4f-7a6bf9763542'
                -
                  - customSelectionLabel
                  - 'Select Document'
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  eb7e7c8e-f03b-44c8-8b3f-f7086707f07a:
    contentColumnType: string
    fieldGroup: null
    handle: linkIcon
    instructions: 'Add a square icon, 300x300px in size. For best results, use a white outlined illustration/lineart.'
    name: 'Link Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:549d1a55-e94b-4c89-9cb9-b1fdac9d417d'
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: 'Add an image'
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:8319fc25-f6c3-449d-a648-e891478b31a6'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
