field: f93e423e-051d-4b4c-bb85-2a5b168296b4
fieldLayouts:
  4c254873-4567-44b6-a087-a6d4cb70b1ea:
    tabs:
      -
        elements:
          -
            fieldUid: c0129db2-783d-4927-b125-203bd8cbdebc
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f602bcbb-5ca9-4e04-8f5c-f031ceb1c2d6
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5b066077-3ce6-4583-af94-4fa87136ab3a
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 912c64e2-6d85-46bb-b826-955df643a5ef
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b278e2a-dc49-4f60-a4bd-18575fb15098
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  4b278e2a-dc49-4f60-a4bd-18575fb15098:
    contentColumnType: string
    fieldGroup: null
    handle: milestoneStarted
    instructions: ''
    name: 'Milestone Started?'
    searchable: false
    settings:
      multi: true
      options:
        -
          __assoc__:
            -
              - label
              - 'Yes'
            -
              - value
              - 'yes'
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Checkboxes
  5b066077-3ce6-4583-af94-4fa87136ab3a:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneLink
    instructions: ''
    name: 'Milestone Link'
    searchable: false
    settings:
      allowCustomText: ''
      allowTarget: ''
      defaultText: ''
      selectLinkText: ''
      types:
        __assoc__:
          -
            - fruitstudios\linkit\models\Email
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Phone
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Url
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - 'https://www.oaklandca.gov'
                -
                  - allowAlias
                  - ''
                -
                  - allowMailto
                  - ''
                -
                  - allowHash
                  - ''
                -
                  - allowPaths
                  - ''
          -
            - fruitstudios\linkit\models\Twitter
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Facebook
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Instagram
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\LinkedIn
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - customPlaceholder
                  - ''
          -
            - fruitstudios\linkit\models\Entry
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'section:fb3b532b-07c0-4cc1-a0ea-a2b75a26cc8f'
                    - 'section:b3411cb1-e860-46ed-9cd6-58cf9b8daacb'
                    - 'section:9da43fd8-c505-4d19-9486-e0cb669c568a'
                    - 'section:8b7c4e26-9aab-4c5d-874e-aee151107de3'
                    - 'section:983c9f6f-9251-4fd3-91e1-b598eccc6a1a'
                    - 'section:28881fc8-3e61-4fdb-a5ee-cce1bab725bf'
                    - 'section:98d541ae-56ee-4c98-ba9c-37438dc485a0'
                    - 'section:24fa116b-8516-4626-84f3-86b685e71071'
                    - 'section:b7e437e1-239f-4c5c-8c62-5f0323f9d22c'
                    - 'section:70778563-6dac-453d-a4b0-5121f3a614b7'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Category
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\Asset
            -
              __assoc__:
                -
                  - enabled
                  - '1'
                -
                  - customLabel
                  - ''
                -
                  - sources
                  -
                    - 'folder:baf733c3-48be-42a7-8b4f-7a6bf9763542'
                -
                  - customSelectionLabel
                  - ''
          -
            - fruitstudios\linkit\models\User
            -
              __assoc__:
                -
                  - enabled
                  - ''
                -
                  - customLabel
                  - ''
                -
                  - sources
                  - '*'
                -
                  - customSelectionLabel
                  - ''
                -
                  - userPath
                  - ''
    translationKeyFormat: null
    translationMethod: none
    type: fruitstudios\linkit\fields\LinkitField
  912c64e2-6d85-46bb-b826-955df643a5ef:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneDescription
    instructions: ''
    name: 'Milestone Description'
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: 'Simple with Links.json'
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c0129db2-783d-4927-b125-203bd8cbdebc:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneDate
    instructions: ''
    name: 'Milestone Date'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f602bcbb-5ca9-4e04-8f5c-f031ceb1c2d6:
    contentColumnType: text
    fieldGroup: null
    handle: milestoneName
    instructions: ''
    name: 'Milestone Name'
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
