enableVersioning: true
handle: boardsCommissions
name: 'Boards & Commissions'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c35d3a93-d7f4-4c37-ae3e-1b4d403311bb:
    enabledByDefault: true
    hasUrls: true
    template: boards-commissions/_entry
    uriFormat: 'boards-commissions/{slug}'
type: channel
