enableVersioning: true
handle: news
name: News
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  c35d3a93-d7f4-4c37-ae3e-1b4d403311bb:
    enabledByDefault: true
    hasUrls: true
    template: news/_entry
    uriFormat: 'news/{postDate.year}/{slug}'
type: channel
